name: webview_dart
description: Dart bindings for webview, A tiny cross-platform webview library to build modern cross-platform GUIs
version: 1.0.0
homepage: https://github.com/shreyassanthu77/webview_dart

environment:
  sdk: '>=2.14.4 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
dependencies: 
  ffi: ^1.1.2
